### ISSUE TITLE
CsvAgent encoding issue when consuming events from FtpsiteAgent

### ISSUE THREAD

**Issue by davidwabnitz** [kreuzwerker/DKT.huginn#1]
#### Test details
- tested on everything up to 0d4695ddf499c3639099394676803689e9da22ea
##### IS
- Issue with transforming encoding from ASCII-8BIT to UTF-8
##### SHOULD
- handle encoding issues gracefully by automatic encoding conversion prior to event handling
#### Steps to reproduce
1. set up FtpsiteAgent to emit events which are consumed by a CsvAgent
2. trigger scenario by adding a file to watched FTP directory
3. will produce exception during receive. See stacktrace:

```
Exception during receive. "\xC3" from ASCII-8BIT to UTF-8: /Users/dw/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:34:in `encode'
/Users/dw/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:34:in `to_json'
```

**Comment by dsander** [comment]
@davidwabnitz Can you upload the CSV file you used?

**Comment by dsander** [comment]
When reading the data directly from the FTP client we can not automatically detect the encoding, when reading non UTF-8 encoded files the `force_encoding` option needs to be set.

**Comment by davidwabnitz** [comment]
closing as fixed
