### ISSUE TITLE
CsvAgent 'use field' option seems to have no effect

### ISSUE THREAD

**Issue by davidwabnitz** [kreuzwerker/DKT.huginn#3]
#### Test details
- tested on everything up to 0d4695ddf499c3639099394676803689e9da22ea
##### IS
- for the CsvAgent the 'use field' option values seem to have no effect: all fields are always parsed and converted to JSON.
##### SHOULD
- CsvAgent should extract data only from the columns configured for the 'use fields' option
#### Steps to reproduce
1. set up CsvAgent in parse mode configuring 'use field' for 2 columns
2. trigger scenario by providing a CSV file with more than 3 columns

**Comment by dsander** [comment]
Can you provide a sample configuration with the used CSV data? When I specify `statecode, county` in `use fields` the event(s) only include the specified keys.

**Comment by davidwabnitz** [comment]
closing. not a bug but wrong configuration.
