### ISSUE TITLE
CsvAgent 'with header' option set to 'false' seems to have no effect

### ISSUE THREAD

**Issue by davidwabnitz** [kreuzwerker/DKT.huginn#4]
#### Test details
- tested on everything up to 0d4695ddf499c3639099394676803689e9da22ea
##### IS
- for the CsvAgent headers are always parsed and converted to JSON.
##### SHOULD
- When 'with header' option is set to false the CsvAgent should ignore the first row in parsing CSV file contents
#### Steps to reproduce
1. set up CsvAgent in parse mode and with 'with header' set to false
2. trigger scenario by providing a CSV 
3. header is parsed

**Comment by dsander** [comment]
Same as for #3 works as expected and tested in the spec, is it related to the encoding issue you had in #1 ?

**Comment by davidwabnitz** [comment]
closing. not a bug but wrong configuration.
