### ISSUE TITLE
LocalFileAgent scheduling is in effect for 'write' use case

### ISSUE THREAD

**Issue by davidwabnitz** [kreuzwerker/DKT.huginn#5]
#### Test details
- tested on everything up to 0d4695ddf499c3639099394676803689e9da22ea
##### IS
- the LocalFileAgent in a 'writing' use case still runs on schedule (independently of any other settings in upstream event producers like 'propagate immediately' set to true)
- this results in the agent running even if there are no events to consume resulting in outputs with 'empty' payloads
##### SHOULD

TBD
Option 1:
- when in 'write' mode (a setting that is currently only implicit by sources being defined but should probably be explicitly set like for CsvAgent) the agent should be triggered by incoming events. 
- if there is a need for scheduling this could be achieved by the trigger agent
  Option 2:
- introduce an 'ignore empty payload' setting. The effect would be that for empty payloads no event will be emitted
#### Steps to reproduce
1. set up CsvAgent in serialize mode with LocalFileAgent consuming the events emitted and writing the contents to a file
2. trigger scenario by serializing a CSV
3. file is written in scheduled intervals independently of the availability of events to be consumed by LocalFileAgent or not

**Comment by dsander** [comment]
> when in 'write' mode (a setting that is currently only implicit by sources being defined but should probably be explicitly set like for CsvAgent) the agent should be triggered by incoming events.

I agree with that, I think what happened is that when the `LocalFileAgent` was scheduled it emitted a file pointer event for the configured path which then might have been picked up by one of your CSV parsing agents.
Having a mode which explicitly sets the agent into `write` or `read`-mode will prevent that.

**Comment by davidwabnitz** [comment]
fixed. closing.
