### ISSUE TITLE
LocalFileAgent overwriting in append mode

### ISSUE THREAD

**Issue by davidwabnitz** [kreuzwerker/DKT.huginn#6]
#### Test details
- tested on everything up to 0d4695ddf499c3639099394676803689e9da22ea
##### IS
- the LocalFileAgent in a 'append' mode overwrites the file configured in 'path' for each event received instead of appending to the file
##### SHOULD
- append when 'append' option is true
#### Steps to reproduce
1. set up CsvAgent in serialize mode with LocalFileAgent consuming the events emitted and writing the contents to a file and set 'append' option to true
2. trigger scenario by serializing a CSV
3. file is overwritten for each incoming event

**Comment by dsander** [comment]
That was a stupid typo.

**Comment by davidwabnitz** [comment]
fixed. closing.
