### ISSUE TITLE
LocalFileAgent throws error for non existing file in write mode

### ISSUE THREAD

**Issue by davidwabnitz** [kreuzwerker/DKT.huginn#7]
#### Test details
- tested on everything up to 0d4695ddf499c3639099394676803689e9da22ea
##### IS
- the LocalFileAgent in a 'writing' use case throws error when file in path does not exist
##### SHOULD
- in write mode a non-existent file should be created before trying to write to it
- no error should be logged for non-existent files in write mode 
#### Steps to reproduce
1. set up CsvAgent in serialize mode with LocalFileAgent consuming the events emitted and writing the contents to a file where the file defined in the 'path' option does not yet exist
2. trigger scenario by serializing a CSV
3. error is logged. it is unclear if the content is written nonetheless

**Comment by dsander** [comment]
It should create file that do not exist already, is it possible the directory of the file path you used was not existing?

If that is the case what is the expected behavior, do we create a error log message or try to create the directory before writing the file?

**Comment by davidwabnitz** [comment]
fixed. closing.
