### ISSUE TITLE
FremeSpotlightAgent language select incorrect

### ISSUE THREAD

**Issue by davidwabnitz** [kreuzwerker/DKT.huginn#8]
#### Bug report
- environment: local development branch, using Google Chrome Canary (latest) on Mac OS X 
- codebase: master at commit bc05de7fd24f6a05aceca3250ccb4fc8360351e9
##### IS
- be en, de, nl, fr, it, es 
##### SHOULD
- en

**Comment by dsander** [comment]
Fixed in the `feature/nlp-agents` branch, which is now ontop of upstream/master again and in https://github.com/kreuzwerker/DKT.huginn_nlp_agents/commit/efbb6b32476a0c47266f438df8c1436bb023479f

**Comment by davidwabnitz** [comment]
fixed. closing
