### ISSUE TITLE
FemeNerAgent language select is missing option for 'ru'

### ISSUE THREAD

**Issue by davidwabnitz** [kreuzwerker/DKT.huginn#9]
#### Bug report
- environment: local development branch, using Google Chrome Canary (latest) on Mac OS X 
- codebase: master at commit bc05de7fd24f6a05aceca3250ccb4fc8360351e9
##### IS
- be en, de, nl, fr, it, es 
##### SHOULD
- be en, de, nl, fr, it, es, ru

**Comment by dsander** [comment]
`ru` is already in the list of supported languages: https://github.com/kreuzwerker/DKT.huginn/blob/bc05de7fd24f6a05aceca3250ccb4fc8360351e9/app/models/agents/freme_ner_agent.rb#L53 The dropdown becomes scrollable with a certain amount of entries, as `ru` is the last one I suspect you did not scroll to the bottom of the list?

**Comment by davidwabnitz** [comment]
ok. didn't know that and will verify that this is the case.

**Comment by davidwabnitz** [comment]
not a bug. closing
